### ISSUE TITLE
Alphabetical order + missing countries

### ISSUE THREAD

**Issue by skarvall** [Palumba-EU/palumba-eu-app-frontend#15]
Hi,

Some countries (English option) are not listed in alphabetical order (attachment 1).

Additionally, Sweden and Belgium are missing in the app (attachment 1 & 2)

<img width="284" alt="Attachment 1" src="https://github.com/Palumba-EU/palumba-eu-app-frontend/assets/94086366/02257b98-7172-406e-8e3b-964f85f0c78f">
<img width="277" alt="Attachment 2" src="https://github.com/Palumba-EU/palumba-eu-app-frontend/assets/94086366/5ba49b5d-bd65-4d8f-8481-d1b23285c6bc">

**Comment by mitch3ls** [comment]
Hello, thank you for contributing so proactively, this is open source! 

We're actively working on fixing those things and will update this issue accordingly

Cheers,
Michael

**Comment by mitch3ls** [comment]
Hey,

Sweden and Belgium are now available in the app and the countries are also sorted in alphabetical order 🎉

Thank you for bringing up the issues!

Best
Michael
